version: '3.4'

services:

    # PHP Service
    app:
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile
        container_name: laravel_porto_app
        hostname: "laravel-porto"
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app-network

    # Nginx Service
    nginx:
        image: nginx:alpine
        container_name: laravel_porto_nginx
        restart: unless-stopped
        tty: true
        ports:
            -  "80:80"
            #-  "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/app_${APP_ENV}.conf:/etc/nginx/conf.d/default.conf
            - ./dhparam:/etc/nginx/dhparam
            - ./certbot/conf/:/etc/nginx/ssl/
            - ./certbot/data:/var/www/certbot
        networks:
            - app-network

    # SSL
    certbot:
        image: certbot/certbot:latest
        profiles: [ "prod" ]
        volumes:
            - ./certbot/conf/:/etc/letsencrypt
            - ./certbot/logs/:/var/log/letsencrypt
            - ./certbot/data:/var/www/certbot

    # MySQL Service
    mysql:
        image: mysql:latest
        container_name: laravel_porto_mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: "fZWhtnqHtJn25j3u3X7mjp9i"
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - mysql-data:/var/lib/mysql/
            - ./docker/mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
        networks:
            - app-network

    # Database management
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: laravel_porto_phpmyadmin
        environment:
            PMA_HOSTS: "mysql"
        ports:
            - "7007:80"
        networks:
            - app-network

    # Mailing Server
    #  mailhog:
    #    image: mailhog/mailhog:latest
    #    container_name: mailhog
    #    logging:
    #      driver: "none"
    #    ports:
    #      - "1025:1025"
    #      - "8025:8025"
    #    networks:
    #      - app-network

    # Redis
    redis:
        image: redis
        container_name: laravel_porto_redis
        volumes:
            - ./redis.conf:/usr/local/etc/redis/redis.conf
        ports:
            - "6379"
        networks:
            - app-network

# Docker Networks
networks:
    app-network:
        driver: bridge

#Volumes
volumes:
    mysql-data:
        driver: local
